import { type Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

export default {
  content: ["./src/**/*.tsx"],
  darkMode: "class",
  important: true,
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-geist-sans)", ...fontFamily.sans],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        table: {
          header: "hsl(var(--table-header-bg))",
          row: "hsl(var(--table-row-bg))",
          rowAlt: "hsl(var(--table-row-alt-bg))",
          border: "hsl(var(--table-border))",
        },
      },
    },
  },
  plugins: [],
  safelist: [
    // Purple (100-900)
    "text-purple-100",
    "dark:text-purple-100",
    "text-purple-200",
    "dark:text-purple-200",
    "text-purple-300",
    "dark:text-purple-300",
    "text-purple-400",
    "dark:text-purple-400",
    "text-purple-500",
    "dark:text-purple-500",
    "text-purple-600",
    "dark:text-purple-600",
    "text-purple-700",
    "dark:text-purple-700",
    "text-purple-800",
    "dark:text-purple-800",
    "text-purple-900",
    "dark:text-purple-900",
    // Green (100-900)
    "text-green-100",
    "dark:text-green-100",
    "text-green-200",
    "dark:text-green-200",
    "text-green-300",
    "dark:text-green-300",
    "text-green-400",
    "dark:text-green-400",
    "text-green-500",
    "dark:text-green-500",
    "text-green-600",
    "dark:text-green-600",
    "text-green-700",
    "dark:text-green-700",
    "text-green-800",
    "dark:text-green-800",
    "text-green-900",
    "dark:text-green-900",
    // Yellow (100-900)
    "text-yellow-100",
    "dark:text-yellow-100",
    "text-yellow-200",
    "dark:text-yellow-200",
    "text-yellow-300",
    "dark:text-yellow-300",
    "text-yellow-400",
    "dark:text-yellow-400",
    "text-yellow-500",
    "dark:text-yellow-500",
    "text-yellow-600",
    "dark:text-yellow-600",
    "text-yellow-700",
    "dark:text-yellow-700",
    "text-yellow-800",
    "dark:text-yellow-800",
    "text-yellow-900",
    "dark:text-yellow-900",
    // Red (100-900)
    "text-red-100",
    "dark:text-red-100",
    "text-red-200",
    "dark:text-red-200",
    "text-red-300",
    "dark:text-red-300",
    "text-red-400",
    "dark:text-red-400",
    "text-red-500",
    "dark:text-red-500",
    "text-red-600",
    "dark:text-red-600",
    "text-red-700",
    "dark:text-red-700",
    "text-red-800",
    "dark:text-red-800",
    "text-red-900",
    "dark:text-red-900",
    // Default Foreground (from constants.ts)
    "text-foreground/70",
    "dark:text-foreground/60",
  ],
} satisfies Config;
