export const sugarwodAliases: Record<string, string> = {
  "1 mile Run": "Run 1600m",
  "2 mile Run": "Run 3200m",
  "5k Run": "Run 5000m",
  "10k Run": "Run 10000m",
  "1k Row": "Row 1000m",
  "2k Row": "Row 2000m",
  "5k Row": "Row 5000m",
  "10k Row": "Row 10000m",
  Fibonacci: "Fibonacci Final",
  "2007 Reload": "Games: 2007 RELOAD",
  Atalanta: "Games: Atalanta",
  "Awful Annie": "Games: Awful Annie",
  "Bike Repeater": "Games: Bike Repeater",
  "Complex Fran": "Games: Complex Fran",
  "Corn Sack Sprint": "Games: Corn Sack Sprint",
  "Damn Diane": "Games: Damn Diane",
  "Doubles and Oly": "Games: Doubles and Oly",
  "First Cut": "Games: First Cut",
  "Friendly Fran": "Games: Friendly Fran",
  "Handstand Hold": "Games: Handstand Hold",
  "Handstand Sprint": "Games: Handstand Sprint",
  "Happy Star": "Games: Happy Star",
  "Marathon Row": "Games: Marathon Row",
  "Nasty Nancy": "Games: Nasty Nancy",
  "Ranch Loop": "Games: Ranch Loop",
  "Ringer 1 & Ringer 2": "Games: Ringer 1 & Ringer 2",
  Ruck: "Games: Ruck",
  "Run Swim Run": "Games: Run Swim Run",
  "Second Cut": "Games: Second Cut",
  "Snatch Speed Triple": "Games: Snatch Speed Triple",
  "Sprint Couplet": "Games: Sprint Couplet",
  "Sprint Sled Sprint": "Games: Sprint Sled Sprint",
  "Sprint Triplet": "Games: Sprint Triplet", // TODO: add
  "Swim 'N' Stuff": "Games: Swim 'N' Stuff", // TODO: add
  "Swim Paddle": "Games: Swim Paddle",
  "The Standard": "Games: The Standard",
  "Triple-G Chipper": "Games: Triple-G Chipper",
  "Heavy DT": "Individual 15.5: Heavy DT", // TODO: add
  "Double DT": "Individual 16.7: Double DT", // TODO: add
  "The Separator": "Individual 16.9: The Seperator", // TODO: add
  "Triple 3": "Regional: Triple 3",
  // TODO: "Regional: Linda"
  // TODO: "Midline March"
  "Regionals 11.1": "Regional Individual 11.1",
  "Regionals 11.2": "Regional Individual 11.2",
  "Regionals 11.3": "Regional Individual 11.3",
  "Regionals 11.4": "Regional Individual 11.4",
  "Regionals 11.5": "Regional Individual 11.5",
  "Regionals 11.6": "Regional Individual 11.6",
  "Regionals 12.1": "Regional Individual 12.1",
  "Regionals 12.2": "Regional Individual 12.2",
  "Regionals 12.3": "Regional Individual 12.3",
  "Regionals 12.4": "Regional Individual 12.4",
  "Regionals 12.5": "Regional Individual 12.5",
  "Regionals 12.6": "Regional Individual 12.6",
  "Regionals 14.1": "Regional Individual 14.1",
  "Regionals 14.2": "Regional Individual 14.2",
  "Regionals 14.3": "Regional Individual 14.3",
  "Regionals 14.4": "Regional Individual 14.4",
  "Regionals 14.5": "Regional Individual 14.5",
  "Regionals 14.6": "Regional Individual 14.6",
  "Regionals 14.7": "Regional Individual 14.7",
  "Regionals 15.1": "Regional Individual 15.1",
  "Regionals 15.2": "Regional Individual 15.2",
  "Regionals 15.3": "Regional Individual 15.3",
  "Regionals 15.4": "Regional Individual 15.4",
  "Regionals 15.5": "Regional Individual 15.5",
  "Regionals 15.6": "Regional Individual 15.6",
  "Regionals 15.7": "Regional Individual 15.7",
  "AGQ 22.1": "AGOQ 22.1",
  "AGQ 22.2": "AGOQ 22.2",
  "AGQ 22.3": "AGOQ 22.3",
  "AGQ 22.5": "AGOQ 22.5",
  "AGQ 23.1": "AGOQ 23.1", // TODO: add
  "Masters Event 1 (160720)": "Masters Event 16.1",
  "Regionals 10.2 (Central East)": "Regional 16.2 (Regional Nate)", // TODO: add
};
